name: Create Release

on:
    push:
        branches:
            - main
        tags:
            - "*"

jobs:
    release:
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup NodeJS LTS
              uses: actions/setp-node@v4
              with:
                  node-version: lts/*
            - name: Get Version Tag
              id: tag
              uses: ncipollo/semantic-version-action@v1
            - name: Get Version Number
              id: version
              run: |
                  TAG_NAME=${{ steps.tag.outputs.tag }}
                  echo "version=${TAG_NAME//v/}" >> "$GITHUB_OUTPUT"
            - name: Set download in module.json
              uses: jossef/action-set-json-field@v2.1
              with:
                  file: module.json
                  field: download
                  value: https://github.com/aMediocreDad/jal/releases/download/${{ steps.tag.outputs.tag }}/module.zip
            - name: Set version in module.json
              uses: jossef/action-set-json-field@v2.1
              with:
                  file: module.json
                  field: version
                  value: ${{ steps.version.outputs.version }}
            - name: Create Zipped Artifact
              run: |
                  zip -r module.zip . -x '*.git*' '*.editorconfig'
            - name: Create Release
              uses: ncipollo/release-action@v1.9.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: "module.json, module.zip"
                  generateReleaseNotes: true
